services:
  speech-service:
    build:
      context: ./speech_service
      dockerfile: Dockerfile

    container_name: speech-service

    ports:
      - "8001:8001"

    volumes:
      - ./speech_service/data/models:/app/data/models
      - ./speech_service/secrets:/app/secrets

    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/secrets/virtual-ai-assistant-492716-cadc67c3a151.json

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

    restart: unless-stopped


  postgres:
    image: postgres:15
    container_name: postgres-db

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: ai_assistant

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d ai_assistant"]
      interval: 60s
      timeout: 5s
      retries: 5

    restart: unless-stopped


volumes:
  postgres_data: